image: golang:1.23-alpine

stages:
  - build
  - release

variables:
  BINARY_NAME: agent
  GIT_STRATEGY: fetch
  GOOS:
    - linux
    - windows
  GOARCH:
    - amd64

build:
  stage: build
  script:
    - mkdir -p build
    - for os in $GOOS; do 
        for arch in $GOARCH; do \
          echo "Building for $os/$arch"; \
          CGO_ENABLED=0 GOOS=$os GOARCH=$arch go build -ldflags "-s -w" \
            -o build/${BINARY_NAME}_$os_$arch main.go
        done
      done
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - branches
    - tags

release:
  image: alpine:latest
  stage: release
  only:
    - tags
  script:
    - echo "Creating GitLab Release for tag $CI_COMMIT_TAG"
    - |
      curl --silent --show-error --fail \
        --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --header "Content-Type: application/json" \
        --data '{
          "name": "'$CI_COMMIT_TAG'",
          "tag_name": "'$CI_COMMIT_TAG'",
          "description": "Release '$CI_COMMIT_TAG'"
        }' \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"
    - |
      for file in build/*; do
        curl --silent --show-error --fail \
          --request POST \
          --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --form "name=$(basename $file)" \
          --form "url=$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/build/$(basename $file)" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
      done